name = "World Creation"
author = "lucaruby"
version = "2.0.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6e61f5c0dcf046c4995583cdee3c16a8945818748932cb6dba0efd7b10517174"

[versions]
fabric = "0.16.5"
minecraft = "1.20.1"
