name = "World Creation"
author = "lucaruby"
version = "2.0.0-RC12"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "001b260a533d118f31500a435c1ddb3e06d3ee7030de4e7375bcaf39c9fbb6b4"

[versions]
fabric = "0.16.2"
minecraft = "1.20.1"
