name = "World Creation"
author = "lucaruby"
version = "2.0.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8383c4c383886b140731f033dface9db6061543b0a534d2207ef1a6bfbce0832"

[versions]
fabric = "0.16.5"
minecraft = "1.20.1"
