name = "World Creation"
author = "lucaruby"
version = "2.0.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9ebce1ce7a10d66692a13eed46313d991ed54e4a90fc98589405e0ada59964df"

[versions]
fabric = "0.16.5"
minecraft = "1.20.1"
